config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # List all tasks
  get "tasks", to: "tasks#index"
  
  # Get the create task form
  get "tasks/new", to: "tasks#new"

  # show individual task details
  get "tasks/:id", to: "tasks#show", as: :task

  # send the new task to be saved
  post "tasks", to: "tasks#create"

  # Make new from with details already in to update
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task

  # Save the updated tasks
  patch "tasks/:id", to: "tasks#update"

  # Destroy tasks
  delete "tasks/:id", to: "tasks#destroy", as: :delete_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(tasks_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Please update your task below:</h2>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h2>My Tasks</h2>
<ul>
  <% @tasks.each do |task| %>
    <li><%=link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

<%= link_to "New task", tasks_new_path %> 

app/views/tasks/new.html.erb
<h2>Enter your task details below:</h2>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<%= @task.title %>
<h3>Task details:</h3>
<%= @task.details %>

<br>
<br>

<%= link_to "Back to all tasks", tasks_path %>


<%= link_to "Edit this task", edit_task_path(@task) %>


<%= link_to "Delete #{@task.title}",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>